
var list = 
	["By age 17, about 80% of males have masturbated, as opposed to 58% females",
	"Every year, up to 1000 people die while trying to strangle themselves during masturbation",
	"Some countries, like the U.K., encourage their teenage population to masturbate",
	"Animals like deer, monkeys, walruses and squirrels have been documented masturbating",
	"The inventor of cornflakes, Dr. John Kellogg, published books on anti-masturbation",
	"More than 7 million units of Fleshlight (male sex toy) have been sold worldwide",
	"Statistics reveal that 53% of American women use toys while masturbating",
	"70% of married people admit to masturbating",
	"Masturbation prevents cervical infections in women",
	"There's no 'normal' amount of masturbation",
	"In North Korea, the punishment for viewing porn is death!",
	"Just about half of the Internet is made up of porn or porn related content",
	"A University of Montreal study found that most guys are exposed to porn for the first time at age 10",
	"The United States is the top producer of pornographic dvds and web material; the second largest is Germany",
	"In fact, every 39 minutes a new porn film is created in the United States",
	"Which coincides with Sex Tracker’s findings of 70% of all internet porn traffic occurring during workdays",
	"10% of adults admit to legitimately have an online porn addiction",
	"Twelve percent of websites on the Internet are pornographic",
	"Around 70% of men aged 18–24 visit porn sites in a typical month",
	"Over 40 million Americans are regular visitors to porn sites",
	"Every second the online porn industry makes over $3,000",
	"Every second, nearly 30,000,000 unique internet users view porn",
	"Nearly 2.5 billion emails per day are pornographic, which is 8% of all emails",
	"Over 35% of all Internet downloads are pornographic",
	"There are over 116,000 searches for “child pornography” every day",
	"Sunday is the most popular day to watch porn. The least popular day of the year is Thanksgiving",
	"The average porn site visit last 6 minutes and 20 seconds",
	"One in three porn visitors is a woman",
	"The word “pornography” first appeared in the Oxford English Dictionary in 1857",
	"The richest porn star is Jenna Jameson",
	"The $3.2 million film 3-D Sex and Zen: Extreme Ecstasy is billed as the world’s first 3D porn film",
	"While 25%–33% of those who watch Internet porn are women, they make up only 2% of paying porn site subscribers",
	"Film production of pornography began immediately after the invention of the motion picture in 1895",
	"The word “clitoris” is Greek for “divine and goddess like”",
	"Married people are more likely to masturbate than people living alone",
	"The fear of having, seeing, or thinking about an erection is called ithyphallophobia",
	"The average man has 11 erections per day and 9 erections a night",
	"Women who went to college are more likely to enjoy receiving and giving oral sex",
	"Approximately 1% of people worldwide identify as asexual",
	"Statistics show that approximately 1 in every 5 Americans has indulged in sex with a colleague at work",
	"Men who help with housework also tend to have more sex",
	"Some people are able to orgasm while working out, thanks to repetitious core movement",
	"During 30 minutes of active sex, the average person burns approximately 200 calories",
	"Approximately 70% of men refuse to have sex during their girlfriend’s period",
	"The most successful X-rated movie in history is Deep Throat",
	"Everyday, there are about 100 million acts of sexual intercourse a day globally",
	"“Nipplegasm” exists, which means that some women can orgasm through nipple stimulation",
	"At least one in 5 people use their smartphones during sex",
	"The average male orgasm lasts 6 seconds. The average female orgasm lasts 20 seconds",
	"People who sleep on their stomachs with their arms above their heads have more sexual dreams",
	"After fingers and vibrators, women choose candles as a sex toys",
	"The most common cause of penile rupture is vigorous masturbation"]


var index = Math.floor(Math.random() * list.length)
	document.write(list[index])
